export const SUN_MASS = 1.989e30;
export const G = 6.67430e-11;

export const primaryLayers = [
    { name: "Planets", icon: "○", src: "/icons/circleUI.png" },
    { name: "Asteroids", icon: "△", src: "/icons/triangleUI.png" },
    { name: "Comets", icon: "□", src: "/icons/squareUI.png" },
    { name: "Spacecrafts", icon: "⬟", src: "/icons/pentagonUI.png" },
];

export const secondaryLayers = [
    { name: "User Interface", icon: null },
    { name: "Labels", icon: null },
    { name: "Icons", icon: null },
    { name: "Orbits", icon: null },
    { name: "Trails", icon: null },
];

export const timeSpeedOptions = [
    { value: -600, label: "-1 year/s" },
    { value: -296, label: "-6 months/s" },
    { value: -148, label: "-3 months/s" },
    { value: -99, label: "-2 months/s" },
    { value: -49, label: "-1 month/s" },
    { value: -35, label: "-3 weeks/s" },
    { value: -23, label: "-2 weeks/s" },
    { value: -12, label: "-1 week/s" },
    { value: -8, label: "-5 days/s" },
    { value: -5, label: "-3 days/s" },
    { value: -3, label: "-2 days/s" },
    { value: -1.64, label: "-1 day/s" },
    { value: -1.44, label: "-21 hrs/s" },
    { value: -1.23, label: "-18 hrs/s" },
    { value: -1.10, label: "-16 hrs/s" },
    { value: -0.89, label: "-13 hrs/s" },
    { value: -0.68, label: "-10 hrs/s" },
    { value: -0.55, label: "-8 hrs/s" },
    { value: -0.34, label: "-5 hrs/s" },
    { value: -0.21, label: "-3 hrs/s" },
    { value: -0.07, label: "-1 hr/s" },
    { value: -0.06, label: "-50 mins/s" },
    { value: -0.05, label: "-40 mins/s" },
    { value: -0.03, label: "-30 mins/s" },
    { value: -0.02, label: "-20 mins/s" },
    { value: -0.01, label: "-10 mins/s" },
    { value: -0.009, label: "-8 mins/s" },
    { value: -0.006, label: "-5 mins/s" },
    { value: -0.003, label: "-3 mins/s" },
    { value: -0.001, label: "-1 min/s" },
    { value: -0.0010, label: "-50 secs/s" },
    { value: -0.0008, label: "-40 secs/s" },
    { value: -0.0006, label: "-30 secs/s" },
    { value: -0.0004, label: "-20 secs/s" },
    { value: -0.0002, label: "-10 secs/s" },
    { value: -0.0001, label: "-5 secs/s" },
    { value: -0.00006, label: "-3 secs/s" },
    { value: 0.00002, label: "Real Rate" },
    { value: 0.00006, label: "3 secs/s" },
    { value: 0.0001, label: "5 secs/s" },
    { value: 0.0002, label: "10 secs/s" },
    { value: 0.0004, label: "20 secs/s" },
    { value: 0.0006, label: "30 secs/s" },
    { value: 0.0008, label: "40 secs/s" },
    { value: 0.0010, label: "50 secs/s" },
    { value: 0.001, label: "1 min/s" },
    { value: 0.003, label: "3 mins/s" },
    { value: 0.006, label: "5 mins/s" },
    { value: 0.009, label: "8 mins/s" },
    { value: 0.01, label: "10 mins/s" },
    { value: 0.02, label: "20 mins/s" },
    { value: 0.03, label: "30 mins/s" },
    { value: 0.05, label: "40 mins/s" },
    { value: 0.06, label: "50 mins/s" },
    { value: 0.07, label: "1 hr/s" },
    { value: 0.21, label: "3 hrs/s" },
    { value: 0.34, label: "5 hrs/s" },
    { value: 0.55, label: "8 hrs/s" },
    { value: 0.68, label: "10 hrs/s" },
    { value: 0.89, label: "13 hrs/s" },
    { value: 1.10, label: "16 hrs/s" },
    { value: 1.23, label: "18 hrs/s" },
    { value: 1.44, label: "21 hrs/s" },
    { value: 1.64, label: "1 day/s" },
    { value: 3, label: "2 days/s" },
    { value: 5, label: "3 days/s" },
    { value: 8, label: "5 days/s" },
    { value: 12, label: "1 week/s" },
    { value: 23, label: "2 weeks/s" },
    { value: 35, label: "3 weeks/s" },
    { value: 49, label: "1 month/s" },
    { value: 99, label: "2 months/s" },
    { value: 148, label: "3 months/s" },
    { value: 296, label: "6 months/s" },
    { value: 600, label: "1 year/s" },
];